### PR TITLE
0.20

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by DeMiro5001** [comment]
`Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.31-1~deb10u1. in /var/www/movim/vendor/composer/platform_check.php on line 24`

Composer helper seems to ignore the phpversion :  
https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_composer/ynh_composer

```
COMPOSER_HOME="$workdir/.composer" \
		php "$workdir/composer.phar" $commands \
		-d "$workdir" --quiet --no-interaction
}
```

Should be

```
COMPOSER_HOME="$workdir/.composer" \
		php$phpversion "$workdir/composer.phar" $commands \
		-d "$workdir" --quiet --no-interaction
}
```

**Comment by ericgaspar** [comment]
Composer helper is now integrated to the core. We are using this PHP helper : https://github.com/YunoHost/yunohost/blob/dev/helpers/php. I am not shure why we get this error...

**Comment by ericgaspar** [comment]
!bullseyetestme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request closed without merging**
