### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
Still RC release...

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]

**Comment by alexAubin** [comment]
Shall we merge this ? :eyes:

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
Quick review, LGTMish, bit embarassed about the data dir being called "cache dir" but i guess it's legacy and boring as hell to rename the setting

**Comment by yalh76** [comment]
I will move that to old-testing to try to upgrade

**Pull request closed without merging**
