### PR TITLE
Change maintainer and fix package linter issues

### PR DESCRIPTION
**Pull request by Jibec**
add myselft as maintainer (please tell if you wish to be part of it), and fix tiny issues detected by package_linter

### CODE REVIEW

**Comment by edhelas** [comment]
Hi,
Thanks for the support on the Yunohost package, I'm ok to move responsibilities of the package on this repository and close the movim/movim_ynh one :)

**Comment by Thatoo** [comment]
Do you plan to work on integration level too? It is level 4 as for today's speaking.

**Comment by frju365** [comment]
I plan to work on the app after the end of this month... so I'm ok to work with you.

**Comment by matlag** [comment]
If I may, what is preventing this to go through at this stage?

**Comment by Jibec** [comment]
Time is the only issue

**Comment by alexAubin** [comment]
Bump, anyone has any idea what we should do we this ? Shall we just yolomerge it ? :/

**Comment by Jibec** [comment]
I'm sure I won't be able to maintain this app. Seeing the next maintainer to reuse my code or not is the same for me.
Just don't put me as maintainer.

**Pull request merged**
